services:
  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080

      # 🔥 troca fácil entre LOCAL e ATLAS
      - MongoDbSettings__ConnectionString=${MONGO_CONN}
      - MongoDbSettings__DatabaseName=ecopulse

    depends_on:
      - mongo
    networks:
      - ecopulse-net

  mongo:
    image: mongo:6
    restart: always
    container_name: ecopulse-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ecopulse-net

volumes:
  mongo_data:

networks:
  ecopulse-net: